name: KageCore
author: Moritz Hein
version: 1.0.1
description: KageCore is a library with useful stuff
website: http://syscy.de
main: de.syscy.kagecore.KageCorePlugin
commands:
  createGUI:
    description: Creates a new gui with the given name.
    usage: /createGUI <guiName>
  editGUI:
    description: Edits the gui with the specified name.
    usage: /editGUI <guiName>
  removeGUI:
    description: Removes the gui with the specified name.
    usage: /removeGUI <guiName>
  showGUI:
    description: Shows the gui with the specified name.
    usage: /showGUI <guiName> (playerName)
  createHGUI:
    description: Creates a new hotbar gui with the given name.
    usage: /createHGUI <guiName>
  editHGUI:
    description: Edits the hotbar gui with the specified name.
    usage: /editHGUI <guiName>
  removeHGUI:
    description: Removes the hotbar gui with the specified name.
    usage: /removeHGUI <guiName> (playerName)
  showHGUI:
    description: Shows the hotbar gui with the specified name.
    usage: /showHGUI <guiName> (playerName)
  hideHGUI:
    description: Hides the current hotbar gui.
    usage: /hideHGUI (playerName)
  bindHotbarToWorld:
    description: Defines the hotbar to always display in the specified world
    usage: /bindHotbarToWorld <hotbar> <world>
  listGUIS:
    description: Lists all currently loaded guis and hotbar guis.
    usage: /listGUIS
permissions:
  bg.*:
    description: Gives access to all commands
    children:
      bg.createGUI: true
      bg.editGUI: true
      bg.removeGUI: true
      bg.showGUI: true
      bg.bindHotbar: true
      bg.listguis: true
  bg.createGUI:
    description: Allows you to create new guis and hotbar guis
    default: false
  bg.editGUI:
    description: Allows you to edit guis and hotbar guis
    default: false
  bg.removeGUI:
    description: Allows you to remove guis and hotbar guis
    default: false
  bg.showGUI:
    description: Allows you to open guis and hotbar guis
    default: false
  bg.bindHotbar:
    description: Allows you to bind a hotbar to a world.
    default: false
  bg.listguis:
    description: Allows you to bind a hotbar to a world.
    default: false
